version: "3.9"

networks:
  default:
    driver: bridge

volumes:
  psql_volume:
    driver: local

services:
  php:
    build: .docker/php
    ports:
    - "8080:80"
    volumes:
    - ./:/var/www/html
    restart: always
  psql:
    image: "postgres:14.4"
    restart: always
    environment:
      POSTGRES_PASSWORD: pass
    volumes:
    - "psql_volume:/var/lib/postgresql/data"
  adminer:
    image: "adminer:4.8.1"
    restart: always
    ports:
      - 8085:8080
  composer:
    image: composer
    command: install
    user: 1000:1000
    volumes:
      - ./:/app

