version: "3.9"

networks:
  default:
    driver: bridge

volumes:
  database:
    driver: local

services:
  php:
    build: .docker/php
    ports:
    - "8080:80"
    volumes:
    - ./:/var/www/html
    restart: always
  db:
    image: "mysql:8.0"
    restart: always
    ports:
    - 36060:3606
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: php_advance
    volumes:
    - "database:/var/lib/mysql"
  adminer:
    image: "adminer:4.8.1"
    restart: always
    ports:
      - 8085:8080
  composer:
    image: composer
    command: install
    user: 1000:1000
    volumes:
      - ./:/app

